[package]
name = "simulation_project"
version = "0.1.0"
edition = "2021"

[dependencies]
petgraph = "0.6"
serde = { version = "1.0", features = ["derive"] }

[lib]
name = "simulation_project"
path = "src/lib.rs"
